spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/line_demo?useSSL=false
    username: line_demo
    password: line@12345


  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    jpa.hibernate.ddl-auto: create